import type { ClientContext } from '@deepseek-ai/dsh-client-runtime/client'

const STYLE_ID = 'dsh-connect-styles'

const CSS = `
.dshc-workbench{width:100%;min-height:100%;box-sizing:border-box;color:var(--dsw-alias-label-primary,#17191c);background:var(--dsw-alias-bg-base,#f6f7f8);padding:28px 32px 40px}
.dshc-page-head{display:flex;align-items:center;justify-content:space-between;gap:24px;max-width:1180px;margin:0 auto 22px}.dshc-page-title{min-width:0}.dshc-page-title h1{margin:0;font-size:22px;line-height:1.3;font-weight:650}.dshc-page-title p{margin:5px 0 0;color:var(--dsw-alias-label-tertiary,#70757d);font-size:13px}.dshc-page-summary{display:flex;align-items:center;gap:16px;flex:0 0 auto;color:var(--dsw-alias-label-tertiary,#70757d);font-size:12px;white-space:nowrap}.dshc-summary-item{display:inline-flex;align-items:baseline;gap:5px;white-space:nowrap}.dshc-summary-item strong{color:var(--dsw-alias-label-primary,#17191c);font-size:20px;font-weight:650}
.dshc-workbench>.dshc-body{max-width:1180px;margin:0 auto;padding:0}
.dshc-card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:14px}.dshc-source-card,.dshc-api-card{min-width:0;border:1px solid var(--dsw-alias-border-l2,#dfe2e6);border-radius:8px;padding:16px;background:var(--dsw-alias-bg-layer-3,#fff);transition:border-color .16s,box-shadow .16s}.dshc-source-card:hover,.dshc-api-card:hover{border-color:var(--dsw-alias-label-dimmed,#aeb3ba);box-shadow:0 5px 16px rgb(23 25 28 / 6%)}
.dshc-source-card-head{display:flex;align-items:center;gap:10px;min-width:0}.dshc-source-card-title{display:flex;flex-direction:column;gap:3px;min-width:0;flex:1}.dshc-source-card-title strong{font-size:14px;font-weight:650;overflow-wrap:anywhere}.dshc-source-card-title span{font-size:11px;color:var(--dsw-alias-label-tertiary,#70757d)}.dshc-db-logo{width:34px;height:34px;border-radius:8px;display:grid;place-items:center;flex:none;background:var(--dsw-alias-bg-layer-1,#f2f3f5)}.dshc-db-logo img{width:22px;height:22px}.dshc-db-logo-mysql{background:#e7f0f7}.dshc-db-logo-postgresql{background:#e9f0f6}.dshc-db-logo-clickhouse{background:#fff1e8}
.dshc-source-address{margin:15px 0 11px;font:11px/1.4 ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--dsw-alias-label-secondary,#4f555d);overflow-wrap:anywhere}.dshc-source-stats{display:flex;align-items:center;flex-wrap:wrap;gap:12px;color:var(--dsw-alias-label-tertiary,#70757d);font-size:11px}.dshc-source-stats strong{color:var(--dsw-alias-label-primary,#17191c);font-size:14px;font-weight:650;margin-right:3px}.dshc-current-object,.dshc-api-description{margin:8px 0 0;color:var(--dsw-alias-label-tertiary,#70757d);font-size:11px;line-height:1.45;overflow-wrap:anywhere}.dshc-card-actions{display:flex;align-items:center;flex-wrap:wrap;gap:6px;margin-top:15px}.dshc-card-actions-muted{margin-top:9px}.dshc-card-actions-muted .dshc-row-meta{margin-left:auto}.dshc-tool-name{display:block;margin-top:11px;padding:6px 8px;border-radius:5px;background:var(--dsw-alias-bg-base,#f4f5f6);font:10px/1.4 ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere;color:var(--dsw-alias-label-secondary,#4f555d)}.dshc-api-method{display:inline-grid;place-items:center;width:43px;height:28px;border-radius:6px;background:var(--dsw-alias-bg-layer-1,#f2f3f5);font:650 10px ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--dsw-alias-label-secondary,#4f555d)}.dshc-api-method[data-method=GET]{color:#147a55;background:#eaf7f0}.dshc-api-method[data-method=POST]{color:#2568a5;background:#eaf2fb}.dshc-api-method[data-method=DELETE]{color:#b23b43;background:#fcedee}
.dshc-card{list-style:none;border:1px solid var(--dsw-alias-border-l2,#dfe2e6);border-radius:8px;background:var(--dsw-alias-bg-layer-3,#fff);color:var(--dsw-alias-label-primary,#17191c);overflow:hidden}
.dshc-card[data-open=true]{border-color:var(--dsw-alias-label-dimmed,#aeb3ba);background:var(--dsw-alias-bg-layer-2,#fafafa)}
.dshc-card-head{width:100%;border:0;background:none;color:inherit;display:flex;align-items:center;gap:12px;padding:14px 16px;text-align:left;cursor:pointer;font:inherit}
.dshc-card-head:focus-visible,.dshc-icon:focus-visible,.dshc-tab:focus-visible{outline:2px solid var(--dsw-alias-brand-primary,#2d6ae3);outline-offset:-2px}
.dshc-card-title{display:flex;flex:1;min-width:0;flex-direction:column;gap:3px}
.dshc-card-title strong{font-size:15px;line-height:1.4;font-weight:600}
.dshc-card-title span{font-size:13px;line-height:1.45;color:var(--dsw-alias-label-tertiary,#70757d)}
.dshc-summary{flex:none;font-size:11px;line-height:18px;color:var(--dsw-alias-label-secondary,#4f555d)}
.dshc-chevron{flex:none;color:var(--dsw-alias-label-tertiary,#70757d);transition:transform .16s}.dshc-chevron-open{transform:rotate(180deg)}
.dshc-body{border-top:1px solid var(--dsw-alias-border-l2,#dfe2e6);padding:0 16px 16px}
.dshc-toolbar{display:flex;align-items:center;gap:8px;padding:12px 0 8px;min-height:44px}
.dshc-tabs{display:flex;align-items:flex-end;gap:20px;align-self:stretch;border-bottom:1px solid var(--dsw-alias-border-l2,#dfe2e6);margin-right:auto}
.dshc-tab{position:relative;border:0;background:none;color:var(--dsw-alias-label-tertiary,#70757d);font:inherit;font-size:13px;line-height:20px;padding:6px 1px 9px;cursor:pointer;white-space:nowrap}
.dshc-tab[data-active=true]{color:var(--dsw-alias-label-primary,#17191c);font-weight:600}.dshc-tab[data-active=true]:after{position:absolute;right:0;bottom:-1px;left:0;height:2px;background:var(--dsw-alias-label-primary,#17191c);content:''}
.dshc-spacer{flex:1}.dshc-icon{width:30px;height:30px;display:inline-grid;place-items:center;border:1px solid var(--dsw-alias-border-l2,#dfe2e6);border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary,#4f555d);cursor:pointer}.dshc-icon:hover:not(:disabled){border-color:var(--dsw-alias-label-dimmed,#aeb3ba);color:var(--dsw-alias-label-primary,#17191c)}.dshc-icon:disabled{opacity:.42;cursor:default}
.dshc-primary,.dshc-secondary,.dshc-danger{min-height:30px;border-radius:6px;padding:5px 11px;font:inherit;font-size:12px;line-height:18px;display:inline-flex;align-items:center;justify-content:center;gap:6px;cursor:pointer;white-space:nowrap}
.dshc-primary{border:1px solid var(--dsw-alias-label-primary,#17191c);background:var(--dsw-alias-label-primary,#17191c);color:var(--dsw-alias-bg-layer-3,#fff)}
.dshc-secondary{border:1px solid var(--dsw-alias-border-l2,#dfe2e6);background:transparent;color:var(--dsw-alias-label-secondary,#4f555d)}
.dshc-danger{border:1px solid color-mix(in srgb,var(--dsw-alias-state-error-primary,#c7353d) 35%,transparent);background:transparent;color:var(--dsw-alias-state-error-primary,#c7353d)}
.dshc-primary:disabled,.dshc-secondary:disabled,.dshc-danger:disabled{opacity:.42;cursor:default}
.dshc-list{border-top:1px solid var(--dsw-alias-border-l2,#dfe2e6)}
.dshc-row{display:grid;grid-template-columns:minmax(150px,1fr) minmax(110px,.7fr) minmax(110px,.7fr) auto;align-items:center;gap:12px;padding:12px 2px;border-bottom:1px solid var(--dsw-alias-border-l1,#eceef0)}.dshc-row:last-child{border-bottom:0}
.dshc-row-main{min-width:0}.dshc-row-main strong{display:block;overflow-wrap:anywhere;font-size:13px;font-weight:600}.dshc-row-main span,.dshc-row-meta{display:block;margin-top:2px;overflow-wrap:anywhere;font-size:11px;color:var(--dsw-alias-label-tertiary,#70757d)}
.dshc-row-actions{display:flex;align-items:center;justify-content:flex-end;gap:5px}
.dshc-badge{display:inline-flex;align-items:center;gap:5px;width:max-content;max-width:100%;border-radius:999px;padding:2px 8px;background:var(--dsw-alias-bg-layer-1,#f2f3f5);color:var(--dsw-alias-label-secondary,#4f555d);font-size:11px;line-height:18px}.dshc-dot{width:6px;height:6px;border-radius:50%;background:currentColor}.dshc-badge[data-tone=success]{color:var(--dsw-alias-state-success-primary,#16835b)}.dshc-badge[data-tone=error]{color:var(--dsw-alias-state-error-primary,#c7353d)}.dshc-badge[data-tone=warn]{color:var(--dsw-alias-state-warn-primary,#a86700)}
.dshc-progress{height:3px;margin-top:7px;border-radius:2px;background:var(--dsw-alias-bg-layer-1,#e9ebee);overflow:hidden}.dshc-progress span{display:block;height:100%;background:var(--dsw-alias-brand-primary,#2d6ae3);transition:width .2s}
.dshc-empty{padding:36px 12px;text-align:center;color:var(--dsw-alias-label-tertiary,#70757d);font-size:13px}.dshc-error,.dshc-notice{margin:10px 0 0;padding:8px 10px;border-radius:6px;font-size:12px;line-height:1.5}.dshc-error{background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#c7353d) 10%,transparent);color:var(--dsw-alias-state-error-primary,#c7353d)}.dshc-notice{background:var(--dsw-alias-bg-layer-1,#f2f3f5);color:var(--dsw-alias-label-secondary,#4f555d)}
.dshc-loading{display:flex;min-height:220px;align-items:center;justify-content:center;gap:9px;color:var(--dsw-alias-label-tertiary,#70757d);font-size:13px}.dshc-loading-compact{min-height:72px}.dshc-spinner{width:16px;height:16px;box-sizing:border-box;border:2px solid var(--dsw-alias-border-l2,#dfe2e6);border-top-color:var(--dsw-alias-label-primary,#17191c);border-radius:50%;animation:dshc-spin .75s linear infinite}@keyframes dshc-spin{to{transform:rotate(360deg)}}
.dshc-modal{width:min(760px,calc(100vw - 32px));max-height:min(820px,calc(100vh - 32px))}.dshc-meta-modal{width:min(1040px,calc(100vw - 32px));max-height:min(820px,calc(100vh - 32px))}.dshc-modal-content{overflow:auto}
.dshc-form{display:flex;flex-direction:column;gap:16px}.dshc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px 16px}.dshc-field{display:flex;min-width:0;flex-direction:column;gap:6px}.dshc-field-wide{grid-column:1/-1}.dshc-field label,.dshc-field-label{font-size:12px;font-weight:600;color:var(--dsw-alias-label-secondary,#4f555d)}.dshc-field small{font-size:11px;color:var(--dsw-alias-label-tertiary,#70757d)}
.dshc-input,.dshc-select,.dshc-textarea{width:100%;box-sizing:border-box;border:1px solid var(--dsw-alias-border-l2,#dfe2e6);border-radius:6px;background:var(--dsw-alias-bg-layer-3,#fff);color:var(--dsw-alias-label-primary,#17191c);font:inherit;font-size:13px}.dshc-input,.dshc-select{height:34px;padding:0 9px}.dshc-textarea{min-height:76px;resize:vertical;padding:8px 9px;line-height:1.5}.dshc-input:focus,.dshc-select:focus,.dshc-textarea:focus{outline:2px solid color-mix(in srgb,var(--dsw-alias-brand-primary,#2d6ae3) 35%,transparent);border-color:var(--dsw-alias-brand-primary,#2d6ae3)}
.dshc-db-picker{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.dshc-db-option{min-width:0;border:1px solid var(--dsw-alias-border-l2,#dfe2e6);border-radius:8px;background:var(--dsw-alias-bg-layer-3,#fff);color:var(--dsw-alias-label-primary,#17191c);padding:10px 8px;display:grid;grid-template-columns:auto 1fr;align-items:center;gap:2px 8px;text-align:left;cursor:pointer}.dshc-db-option:hover{border-color:var(--dsw-alias-label-dimmed,#aeb3ba)}.dshc-db-option[data-active=true]{border-color:var(--dsw-alias-brand-primary,#2d6ae3);box-shadow:inset 0 0 0 1px var(--dsw-alias-brand-primary,#2d6ae3)}.dshc-db-option .dshc-db-logo{grid-row:1/3}.dshc-db-option>span{font-size:12px;font-weight:650;overflow-wrap:anywhere}.dshc-db-option>small{font-size:10px;color:var(--dsw-alias-label-tertiary,#70757d)}
.dshc-checks{display:flex;align-items:center;flex-wrap:wrap;gap:14px}.dshc-check{display:inline-flex;align-items:center;gap:7px;font-size:12px;color:var(--dsw-alias-label-secondary,#4f555d)}.dshc-check input{width:15px;height:15px;accent-color:var(--dsw-alias-brand-primary,#2d6ae3)}
.dshc-form-footer{display:flex;align-items:center;justify-content:flex-end;gap:8px}.dshc-form-error{margin-right:auto;font-size:12px;color:var(--dsw-alias-state-error-primary,#c7353d)}
.dshc-section-title{display:flex;align-items:center;justify-content:space-between;gap:12px;padding-top:4px;border-top:1px solid var(--dsw-alias-border-l1,#eceef0)}.dshc-section-title strong{font-size:12px}.dshc-param-list{display:flex;flex-direction:column;gap:8px}.dshc-param{display:grid;grid-template-columns:minmax(110px,1.1fr) minmax(90px,.8fr) minmax(90px,.8fr) auto auto;align-items:center;gap:7px}.dshc-param .dshc-input,.dshc-param .dshc-select{height:32px;font-size:12px}.dshc-param-desc{grid-column:1/5}
.dshc-test-result{max-height:240px;overflow:auto;margin:0;padding:10px;border-radius:6px;background:var(--dsw-alias-bg-base,#f4f5f6);font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere}
.dshc-meta-layout{display:grid;grid-template-columns:minmax(210px,.7fr) minmax(0,1.6fr);gap:16px;min-height:420px}.dshc-meta-side{border-right:1px solid var(--dsw-alias-border-l2,#dfe2e6);padding-right:14px}.dshc-meta-search{margin-bottom:8px}.dshc-search-wrap{position:relative;display:block}.dshc-search-wrap svg{position:absolute;left:8px;top:9px}.dshc-search-wrap .dshc-input{padding-left:30px}.dshc-meta-list{max-height:540px;overflow:auto}.dshc-meta-item{width:100%;border:0;border-bottom:1px solid var(--dsw-alias-border-l1,#eceef0);background:transparent;color:inherit;text-align:left;padding:9px 4px;cursor:pointer}.dshc-meta-item[data-active=true]{background:var(--dsw-alias-bg-layer-1,#f2f3f5)}.dshc-meta-item strong{display:block;font-size:12px;overflow-wrap:anywhere}.dshc-meta-item span{font-size:11px;color:var(--dsw-alias-label-tertiary,#70757d)}.dshc-meta-detail{min-width:0;overflow:auto}.dshc-meta-detail h3{margin:0 0 4px;font-size:15px}.dshc-meta-detail p{margin:4px 0 12px;font-size:12px;line-height:1.55;color:var(--dsw-alias-label-secondary,#4f555d)}
.dshc-table{width:100%;border-collapse:collapse;font-size:11px}.dshc-table th,.dshc-table td{padding:7px 8px;border-bottom:1px solid var(--dsw-alias-border-l1,#eceef0);text-align:left;vertical-align:top;overflow-wrap:anywhere}.dshc-table th{color:var(--dsw-alias-label-tertiary,#70757d);font-weight:600}.dshc-code{max-height:220px;overflow:auto;padding:10px;border-radius:6px;background:var(--dsw-alias-bg-base,#f4f5f6);font:11px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere}.dshc-detail-title{margin:16px 0 7px;font-size:12px;font-weight:600}
.dshc-governance-section{display:flex;flex-direction:column;gap:10px;padding-top:16px}.dshc-governance-row{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0;padding:10px 2px;border-bottom:1px solid var(--dsw-alias-border-l1,#eceef0)}.dshc-governance-row>div{min-width:0}.dshc-governance-row strong{display:block;font-size:12px;overflow-wrap:anywhere}.dshc-governance-row small{display:block;margin-top:3px;color:var(--dsw-alias-label-tertiary,#70757d);font-size:11px;line-height:1.45;overflow-wrap:anywhere}.dshc-sql-editor{min-height:150px;font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.dshc-query-error{margin-top:auto}
.dshc-load-more{align-self:center;margin-top:4px}.dshc-governance-layout{display:grid;grid-template-columns:250px minmax(0,1fr);min-height:540px;border-top:1px solid var(--dsw-alias-border-l2,#dfe2e6);margin-top:12px}.dshc-governance-sidebar{min-width:0;padding:14px 12px 0 0;border-right:1px solid var(--dsw-alias-border-l2,#dfe2e6)}.dshc-table-search{display:flex;align-items:center;gap:6px;height:32px;padding:0 9px;border:1px solid var(--dsw-alias-border-l2,#dfe2e6);border-radius:6px;color:var(--dsw-alias-label-tertiary,#70757d)}.dshc-table-search input{width:100%;min-width:0;border:0;outline:0;background:transparent;color:inherit;font:inherit;font-size:12px}.dshc-governance-table-list{display:flex;flex-direction:column;gap:3px;margin-top:10px;max-height:470px;overflow:auto}.dshc-governance-table{display:flex;flex-direction:column;gap:3px;width:100%;padding:9px 10px;border:1px solid transparent;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary,#4f555d);text-align:left;cursor:pointer}.dshc-governance-table:hover{background:var(--dsw-alias-bg-layer-1,#f2f3f5)}.dshc-governance-table[data-active=true]{border-color:var(--dsw-alias-border-l2,#dfe2e6);background:var(--dsw-alias-bg-layer-1,#f2f3f5);color:var(--dsw-alias-label-primary,#17191c)}.dshc-governance-table strong{font-size:12px;overflow-wrap:anywhere}.dshc-governance-table span{font-size:11px;line-height:1.4;color:var(--dsw-alias-label-tertiary,#70757d);overflow-wrap:anywhere}.dshc-governance-content{min-width:0;padding:14px 0 0 20px}.dshc-governance-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.dshc-governance-heading>div{min-width:0}.dshc-governance-heading strong,.dshc-governance-heading span{display:block;overflow-wrap:anywhere}.dshc-governance-heading strong{font-size:15px}.dshc-governance-heading>div span{margin-top:3px;color:var(--dsw-alias-label-tertiary,#70757d);font-size:11px}.dshc-governance-tabs{margin-top:15px;margin-right:0;gap:18px}.dshc-governance-form{padding-top:18px}.dshc-form-action{align-self:flex-start}
@media(max-width:720px){.dshc-workbench{position:fixed;inset:78px 24px 24px;z-index:1;min-height:0;overflow:auto;padding:16px 12px 28px;background:var(--dsw-alias-bg-layer-3,#fff)}.dshc-page-head{align-items:flex-start;flex-direction:column;gap:14px}.dshc-page-title{align-items:flex-start}.dshc-page-title p{font-size:12px}.dshc-page-summary{padding-left:0}.dshc-body{padding:0}.dshc-toolbar{flex-wrap:wrap}.dshc-tabs{width:100%;order:2;gap:14px;overflow-x:auto}.dshc-card-grid{grid-template-columns:1fr}.dshc-row{grid-template-columns:minmax(0,1fr) auto}.dshc-row-meta{display:none}.dshc-meta-layout{grid-template-columns:1fr}.dshc-meta-side{border-right:0;border-bottom:1px solid var(--dsw-alias-border-l2,#dfe2e6);padding:0 0 12px}.dshc-meta-list{max-height:180px}.dshc-grid{grid-template-columns:1fr}.dshc-field-wide{grid-column:auto}.dshc-db-picker{grid-template-columns:1fr}.dshc-param{grid-template-columns:1fr 1fr}.dshc-param-desc{grid-column:1/3}.dshc-param .dshc-icon{justify-self:end}.dshc-summary{display:none}.dshc-governance-row{align-items:flex-start}.dshc-governance-row .dshc-badge{flex:none}.dshc-governance-layout{grid-template-columns:1fr}.dshc-governance-sidebar{padding:12px 0;border-right:0;border-bottom:1px solid var(--dsw-alias-border-l2,#dfe2e6)}.dshc-governance-table-list{max-height:180px}.dshc-governance-content{padding:14px 0 0}}
@media(max-width:720px){.dshc-workbench{width:auto}}
`

export function installConnectStyles(ctx: ClientContext): void {
  if (typeof document === 'undefined' || document.getElementById(STYLE_ID) !== null) return
  const style = document.createElement('style')
  style.id = STYLE_ID
  style.textContent = CSS
  document.head.append(style)
  ctx.effect(() => () => { style.remove() }, 'dsh-connect styles')
}
